name: Spell Check

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run spellcheck
      uses: rojopolis/spellcheck-github-actions@0.37.0
